//go:build !ignore_autogenerated

/*
Copyright 2024 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRoleStatus) DeepCopyInto(out *ClusterRoleStatus) {
	*out = *in
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Created.DeepCopyInto(&out.Created)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRoleStatus.
func (in *ClusterRoleStatus) DeepCopy() *ClusterRoleStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetectedOperator) DeepCopyInto(out *DetectedOperator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetectedOperator.
func (in *DetectedOperator) DeepCopy() *DetectedOperator {
	if in == nil {
		return nil
	}
	out := new(DetectedOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetectedOperatorsStatus) DeepCopyInto(out *DetectedOperatorsStatus) {
	*out = *in
	out.CertManager = in.CertManager
	out.ExternalSecrets = in.ExternalSecrets
	out.SecretsStoreCSI = in.SecretsStoreCSI
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetectedOperatorsStatus.
func (in *DetectedOperatorsStatus) DeepCopy() *DetectedOperatorsStatus {
	if in == nil {
		return nil
	}
	out := new(DetectedOperatorsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureConfig) DeepCopyInto(out *FeatureConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureConfig.
func (in *FeatureConfig) DeepCopy() *FeatureConfig {
	if in == nil {
		return nil
	}
	out := new(FeatureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturesConfig) DeepCopyInto(out *FeaturesConfig) {
	*out = *in
	out.Delete = in.Delete
	out.Create = in.Create
	out.Edit = in.Edit
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturesConfig.
func (in *FeaturesConfig) DeepCopy() *FeaturesConfig {
	if in == nil {
		return nil
	}
	out := new(FeaturesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorConfig) DeepCopyInto(out *OperatorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorConfig.
func (in *OperatorConfig) DeepCopy() *OperatorConfig {
	if in == nil {
		return nil
	}
	out := new(OperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorsConfig) DeepCopyInto(out *OperatorsConfig) {
	*out = *in
	out.CertManager = in.CertManager
	out.ExternalSecrets = in.ExternalSecrets
	out.SecretsStoreCSI = in.SecretsStoreCSI
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorsConfig.
func (in *OperatorsConfig) DeepCopy() *OperatorsConfig {
	if in == nil {
		return nil
	}
	out := new(OperatorsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginConfig) DeepCopyInto(out *PluginConfig) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginConfig.
func (in *PluginConfig) DeepCopy() *PluginConfig {
	if in == nil {
		return nil
	}
	out := new(PluginConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginStatus) DeepCopyInto(out *PluginStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginStatus.
func (in *PluginStatus) DeepCopy() *PluginStatus {
	if in == nil {
		return nil
	}
	out := new(PluginStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACConfig) DeepCopyInto(out *RBACConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACConfig.
func (in *RBACConfig) DeepCopy() *RBACConfig {
	if in == nil {
		return nil
	}
	out := new(RBACConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACStatus) DeepCopyInto(out *RBACStatus) {
	*out = *in
	if in.ClusterRoles != nil {
		in, out := &in.ClusterRoles, &out.ClusterRoles
		*out = make([]ClusterRoleStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACStatus.
func (in *RBACStatus) DeepCopy() *RBACStatus {
	if in == nil {
		return nil
	}
	out := new(RBACStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceConfig) DeepCopyInto(out *ResourceConfig) {
	*out = *in
	out.Requests = in.Requests
	out.Limits = in.Limits
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceConfig.
func (in *ResourceConfig) DeepCopy() *ResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsManagementConfig) DeepCopyInto(out *SecretsManagementConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsManagementConfig.
func (in *SecretsManagementConfig) DeepCopy() *SecretsManagementConfig {
	if in == nil {
		return nil
	}
	out := new(SecretsManagementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretsManagementConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsManagementConfigList) DeepCopyInto(out *SecretsManagementConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretsManagementConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsManagementConfigList.
func (in *SecretsManagementConfigList) DeepCopy() *SecretsManagementConfigList {
	if in == nil {
		return nil
	}
	out := new(SecretsManagementConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretsManagementConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsManagementConfigSpec) DeepCopyInto(out *SecretsManagementConfigSpec) {
	*out = *in
	out.Features = in.Features
	out.RBAC = in.RBAC
	out.Plugin = in.Plugin
	out.Operators = in.Operators
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsManagementConfigSpec.
func (in *SecretsManagementConfigSpec) DeepCopy() *SecretsManagementConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SecretsManagementConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsManagementConfigStatus) DeepCopyInto(out *SecretsManagementConfigStatus) {
	*out = *in
	in.RBAC.DeepCopyInto(&out.RBAC)
	out.Plugin = in.Plugin
	out.DetectedOperators = in.DetectedOperators
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsManagementConfigStatus.
func (in *SecretsManagementConfigStatus) DeepCopy() *SecretsManagementConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SecretsManagementConfigStatus)
	in.DeepCopyInto(out)
	return out
}
